# ===== build stage =====
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copia apenas os csproj primeiro (melhora cache)
COPY ["Sales.Api/Sales.Api.csproj", "Sales.Api/"]
COPY ["Sales.Application/Sales.Application.csproj", "Sales.Application/"]
COPY ["Sales.Domain/Sales.Domain.csproj", "Sales.Domain/"]
COPY ["Sales.Infraestructure/Sales.Infrastructure.csproj", "Sales.Infraestructure/"]

RUN dotnet restore "Sales.Api/Sales.Api.csproj"

# Copia o restante do cdigo
COPY . .

RUN dotnet publish "Sales.Api/Sales.Api.csproj" -c Release -o /app/publish

# ===== runtime stage =====
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "Sales.Api.dll"]
